---
abstract: 'Locale::CLDR - Data Package Locales::Br.pm'
author:
  - 'John Imrie <john.imrie1@gmail.com>'
build_requires:
  Test::Exception: '0'
  Test::More: '0.98'
  ok: '0'
configure_requires:
  Module::Build: '0.40'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Locale-CLDR-Locales-Br.pm
provides:
  Locale::CLDR::Locales::Br:
    file: lib/Locale/CLDR/Locales/Br.pm
    version: v0.26.8
  Locale::CLDR::Locales::Br::Any:
    file: lib/Locale/CLDR/Locales/Br/Any.pm
    version: v0.26.8
  Locale::CLDR::Locales::Br::Any::Fr:
    file: lib/Locale/CLDR/Locales/Br/Any/Fr.pm
    version: v0.26.8
requires:
  DateTime: '0.72'
  Locale::CLDR: '0.026008'
  Moose: '2.0401'
  MooseX::ClassAttribute: '0.26'
  perl: v5.10.0
  version: '0.95'
resources:
  license: http://dev.perl.org/licenses/
version: v0.26.8
